spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  frontend-url: ${SPRING_FRONTEND_URL}
  api-key: ${SPRING_API_KEY}

server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true